# Generated by Django 4.1.7 on 2023-03-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=60)),
                ('category_desc', models.CharField(max_length=50)),
                ('catefory_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
