# Generated by Django 4.1.7 on 2023-03-04 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='catefory_image',
            new_name='category_image',
        ),
    ]
