# Generated by Django 4.1.7 on 2023-03-08 18:31

from django.db import migrations, models
import django.db.models.deletion
import hotelbooking.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('item_name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room_view',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('room_name', models.CharField(max_length=50)),
                ('room_price', models.FloatField(default=0)),
                ('max_person', models.IntegerField(default=1)),
                ('room_size', models.IntegerField()),
                ('room_desc', models.TextField()),
                ('room_bed', models.IntegerField(default=1)),
                ('room_image', models.ImageField(upload_to=None)),
                ('room_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelbooking.room_category')),
                ('room_view', models.ManyToManyField(to='hotelbooking.room_view')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=100)),
                ('package_image', models.ImageField(upload_to=None, verbose_name=hotelbooking.models.Room)),
                ('package_item', models.ManyToManyField(to='hotelbooking.package_item')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelbooking.room')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
