# Generated by Django 4.1.7 on 2023-03-21 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hotelbooking", "0002_alter_package_package_image_booking"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room_category",
            options={"ordering": ["id"]},
        ),
        migrations.CreateModel(
            name="Package_Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(blank=True, default=True)),
                ("name", models.CharField(max_length=50)),
                ("phone_number", models.CharField(max_length=50)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hotelbooking.package",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
