# Generated by Django 4.2.1 on 2024-09-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotelbooking", "0007_alter_room_room_desc"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(blank=True, default=True)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=15)),
                ("subject", models.CharField(max_length=100)),
                ("message", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
